# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  enable = config.custom.device == "lenovo-laptop";
in {
  config = lib.mkIf enable {
    # System settings
    custom.gpu = "intel";
    custom.cpu = "intel";
    # custom.gui = "wayland";
    custom.gui = "hm-wayland";
  };
}
