# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  boot.initrd.luks.devices."luks".device = "/dev/disk/by-uuid/04f23024-ffa1-4fd7-8b94-ec8d0269cbbd";

  fileSystems = {
    "/boot" = {
      device = "/dev/disk/by-uuid/D430-45C2";
      fsType = "vfat";
    };

    "/" = {
      device = "/dev/disk/by-uuid/7eafb9a5-b234-4684-8c3e-0ff1b0fc7191";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/7eafb9a5-b234-4684-8c3e-0ff1b0fc7191";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/7eafb9a5-b234-4684-8c3e-0ff1b0fc7191";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

    "/var/log" = {
      device = "/dev/disk/by-uuid/7eafb9a5-b234-4684-8c3e-0ff1b0fc7191";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

    "/home/tm/games" = {
      device = "/dev/disk/by-partuuid/63d76ef1-f532-5946-a17e-ad4079f61f09";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" ];
    };

    "/home/tm/docs" = {
      device = "/dev/disk/by-partuuid/425a0f3a-1f77-4d36-8d13-19ffba02ec0c";
      fsType = "exfat";
      options = [ "defaults" "uid=1000" "gid=100" ];
    };
  };


  swapDevices = [{
    device = "/dev/disk/by-uuid/002b659d-f634-4cc4-8c97-9b3be20b9bfb";
  }];

  # System settings
  custom.gpu = "amd";
  custom.cpu = "amd";
  custom.gui = "wayland";
  #custom.gui = "hm-wayland";
  custom.useUEFI = true;
  custom.bluetooth = true;
  custom.enableVirtualisation = true;

  networking.interfaces.eno1.useDHCP = true;
  #networking.interfaces.enp11s0f3u3u4u4.useDHCP = true;
}
