# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  myTools = pkgs.myTools { inherit config pkgs lib; };
in {
  # File systems configuration for using the installer's partition layout
  fileSystems = {
    # Prior to 19.09, the boot partition was hosted on the smaller first partition
    # Starting with 19.09, the /boot folder is on the main bigger partition.
    # The following is to be used only with older images.
    /*
    "/boot" = {
      device = "/dev/disk/by-label/NIXOS_BOOT";
      fsType = "vfat";
    };
    */
    "/" = {
      device = "/dev/disk/by-label/NIXOS_SD";
      fsType = "ext4";
    };
  };

  #TODO rework
  hardware.raspberry-pi."2" = {
    audio.enable = false;
    dwc2 = {
      enable = false;
    };
    i2c0.enable = false;
    i2c1.enable = false;
    poe-hat.enable = false;
    pwm0.enable = false;
    tc358743.enable = false;
    fkms-3d = {
      enable = false;
    };
  };

  custom.grub = {
    enable = false;
    #useUEFI = false;
  };
  custom.cpuFreqGovernor = "ondemand";
  custom.enableVirtualisation = false;
  custom.adb = "disabled";
  custom.audio = {
    backend = "none";
  };
  custom.smartcards = false;
  custom.networking = {
    wifiSupport = false;
    withNetworkManager = false;
    openvpn.client = {
      enable = false;
      autoConnect = false;
    };
  };
  custom.security = {
    gnupg.enable = false;
    usbguard = {
      enforceRules = false;
      #fixedRules = myTools.getSecret ../. "usbguard-rules.nix";
    };
  };
  custom.internationalization = {
    defaultLcTime = "de_DE.UTF-8";
    defaultLcPaper = "de_DE.UTF-8";
    defaultLcMeasurement = "de_DE.UTF-8";
  };

  custom.sshServer = {
    enable = true;
  };

  networking.interfaces.eth0.useDHCP = true;

  # Disable the dhcp client for our AP interface!
  #networking.interfaces.wlan0.useDHCP = true;
  #networking.wireless.interfaces = [
  #  "wlan0"
  #];

  services.octoprint = {
    enable = true;
    plugins = plugins: with plugins; [
      uploadanything
      themeify
      webcamtab
      taborder
      simpleemergencystop
      resource_monitor
      psucontrol
      printtimegenius
      navbartemp
      multipleupload
      heatertimeout
      gcodeeditor
      floatingnavbar
      excluderegion
      enclosure
      emergencystopsimplified
      bltouch
      autoscroll
      octolapse
      bedlevelvisualizer
      bedlevelingwizard
      arc_welder
      octoprint-dashboard
      multilineterminal
      displaylayerprogress
    ];
  };
  services.klipper = {
    enable = true;
    octoprintIntegration = true;
    settings = let 
      stepperSettings = { step_pin, dir_pin, enable_pin, rotation_distance ? 40}: {
        inherit step_pin dir_pin enable_pin rotation_distance;
        microsteps = 16;
      };

      tmc2208Conf = uart_pin: {
        inherit uart_pin;
        run_current = 0.580;
        stealthchop_threshold = 999999;
      };
    in {
      # This file contains common pin mappings for the BIGTREETECH SKR E3
      # DIP. To use this config, the firmware should be compiled for the
      # STM32F103 with a "28KiB bootloader" and USB communication. Also,
      # select "Enable extra low-level configuration options" and configure
      # "GPIO pins to set at micro-controller startup" to "!PC13".

      # The "make flash" command does not work on the SKR E3 DIP. Instead,
      # after running "make", copy the generated "out/klipper.bin" file to a
      # file named "firmware.bin" on an SD card and then restart the SKR E3
      # DIP with that SD card.

      # See docs/Config_Reference.md for a description of parameters.

      # Note: This board has a design flaw in its thermistor circuits that
      # cause inaccurate temperatures (most noticeable at low temperatures).

      stepper_x = (stepperSettings {
        step_pin = "PC6";
        dir_pin = "!PB15";
        enable_pin = "!PC7";
      }) // {
        endstop_pin = "^PC1";
        position_endstop = 0;
        position_max = 235;
        homing_speed = 50;
      };

      stepper_y = (stepperSettings {
        step_pin = "PB13";
        dir_pin = "!PB12";
        enable_pin = "!PB14";
      }) // {
        endstop_pin = "^PC0";
        position_endstop = 0;
        position_max = 235;
        homing_speed = 50;
      };

      stepper_z = (stepperSettings {
        step_pin = "PB10";
        dir_pin = "PB2";
        enable_pin = "!PB11";
        rotation_distance = 8;
      }) // {
        endstop_pin = "^PC15";
        position_endstop = 0;
        position_max = 250;
      };

      extruder = (stepperSettings {
        step_pin = "PB0";
        dir_pin = "!PC5";
        enable_pin = "!PB1";
        rotation_distance = 33.5;
      }) // {
        nozzle_diameter = 0.4;
        filament_diameter = 1.75;
        heater_pin = "PC8";
        sensor_type = "EPCOS 100K B57560G104F";
        sensor_pin = "PA0";
        control = "pid";
        pid_Kp = 21.527;
        pid_Ki = 1.063;
        pid_Kd = 108.982;
        min_temp = 0;
        max_temp = 250;
      };

      heater_bed = {
        heater_pin = "PC9";
        sensor_type = "ATC Semitec 104GT-2";
        sensor_pin = "PC3";
        control = "pid";
        pid_Kp = 54.027;
        pid_Ki = 0.770;
        pid_Kd = 948.182;
        min_temp = 0;
        max_temp = 130;
      };

      fan = {
        pin = "PA8";
      };

      # mcu = {
      #   serial = "/dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00";
      # };

      mcu.serial = "/dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00";

      printer = {
        kinematics = "cartesian";
        max_velocity = 300;
        max_accel = 3000;
        max_z_velocity = 5;
        max_z_accel = 100;
      };

      # TODO no idea how this can be realized with the current klipper service module!
      "static_digital_output usb_pullup_enable" = {
        pins = "!PC13";
      };

      ########################################
      # TMC2208 configuration
      ########################################

      # TODO compare current values with the ones set in Marlin!
      "tmc2208 stepper_x" = tmc2208Conf "PC10";
      "tmc2208 stepper_y" = tmc2208Conf "PC11";
      "tmc2208 stepper_z" = tmc2208Conf "PC12";

      "tmc2208 extruder" = (tmc2208Conf "PD2") // { run_current = 0.650; };

      ########################################
      # EXP1 (display) pins
      ########################################

      board_pins = {
        # EXP1 header
        aliases = "EXP1_1=PA15, EXP1_3=PA9, EXP1_5=PA10, EXP1_7=PB8, EXP1_9=<GND>, EXP1_2=PB6, EXP1_4=<RST>, EXP1_6=PB9, EXP1_8=PB7, EXP1_10=<5V>";
      };

      # See the sample-lcd.cfg file for definitions of common LCD displays.
    };
  };

}
