# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  myTools = pkgs.myTools { inherit config pkgs lib; };
in {
  # File systems configuration for using the installer's partition layout
  fileSystems = {
    # Prior to 19.09, the boot partition was hosted on the smaller first partition
    # Starting with 19.09, the /boot folder is on the main bigger partition.
    # The following is to be used only with older images.
    /*
    "/boot" = {
      device = "/dev/disk/by-label/NIXOS_BOOT";
      fsType = "vfat";
    };
    */
    "/" = {
      device = "/dev/disk/by-label/NIXOS_SD";
      fsType = "ext4";
    };
  };

  hardware.raspberry-pi."4" = {
    audio.enable = false;
    dwc2 = {
      enable = false;
    };
    i2c0.enable = false;
    i2c1.enable = false;
    poe-hat.enable = false;
    pwm0.enable = false;
    tc358743.enable = false;
    fkms-3d = {
      enable = false;
    };
  };

  custom.grub = {
    enable = false;
    #useUEFI = false;
  };
  custom.cpuFreqGovernor = "ondemand";
  custom.enableVirtualisation = false;
  custom.adb = "disabled";
  custom.audio = {
    backend = "none";
  };
  custom.smartcards = false;
  custom.networking = {
    wifiSupport = false;
    withNetworkManager = false;
  };
  custom.security = {
    gnupg.enable = false;
    usbguard = {
      enforceRules = false;
      #fixedRules = myTools.getSecret ../. "usbguard-rules.nix";
    };
  };
  custom.internationalization = {
    defaultLcTime = "de_DE.UTF-8";
    defaultLcPaper = "de_DE.UTF-8";
    defaultLcMeasurement = "de_DE.UTF-8";
  };

  custom.sshServer = {
    enable = true;
    authorizedKeys = [
    ];
  };

  networking.interfaces.eth0.useDHCP = true;
  networking.interfaces.wlan0.useDHCP = true;
  networking.wireless.interfaces = [
    "wlan0"
  ];
}
